### ISSUE TITLE
Strange framerate spiking with certain things.

### ISSUE THREAD

**Issue by mrwallace888** [Blu-x92/simfphys_base#48]
Yeah I don't know what causes it. I've got only a handful of simfphys cars, but none of them specifically are causing conflicts. Just if I have a certain number. But basically, performance is fine. But once I spawn a simfphys car in, it'll be smooth, but then it'll keep creating a massive spike for a hot second after a certain amount of time every time. So like it'll be 60 (what it's limited to) then dip to like 0 for a split second, then go back up to 60. It's at a constant interval.

Also, every time I turn on/off my lights, or honk/stop honking the horn, it causes a massive game freeze every time in that regard too.

Console's not showing anything either.

**Comment by Blu-x92** [comment]
issue on your side

**Comment by mrwallace888** [comment]
How does that help?

**Comment by Rubberbandits** [comment]
"issue is on your side"

no, the issue is that this guy uses projected textures and dynamic lights that destroy framerate, pairs loops instead of ipairs, numerical iterators using table.Count (which just fucking counts the table using a pairs loop, again.)

everything in simfphys destroys not only clientside framerate, but server performance as well.

The GetEnginePos function within itself is the main issue with clientside FPS, as soon as I cached the value returned by GetAttachment, clientside FPS doubled.

LOCALIZE YOUR META METHODS.

**Comment by Blu-x92** [comment]
nice, but this will not cause his specific framedrop issue. Feel free to make a pullrequest tho. Thanks 👌
