### ISSUE TITLE
Strange message 

### ISSUE THREAD

**Issue by 0xadg** [Blu-x92/simfphys_base#73]
That's more of a question rather than an issue, but what's the purpose of this piece of code in the `init.lua` of `gmod_sent_vehicle_fphysics_base` entity (line 1115):
```
if self.PhysicsEnabled ~= false then
			for i = 1, table.Count( self.Wheels ) do
				local Wheel = self.Wheels[i]
				if IsValid(Wheel) then
					Wheel:GetPhysicsObject():SetMaterial("friction_00")
					if Wheel:GetPhysicsObject():GetMaterial() ~= "friction_00" then
						print("(SIMFPHYS) ERROR! MISSING ''friction_00'' PHYSPROP-MATERIAL!!! THIS SHOULD NEVER HAPPEN!! CLEAN YOUR GMOD!! DON'T USE CONTENT OF GAMES YOU DON'T OWN!! DON'T EVEN BOTHER REPORTING THIS ISSUE, BECAUSE ONLY YOU CAN FIX THIS AS THIS IS AN ISSUE WITH YOUR GAME!!!!")
						sound.Play( "common/bugreporter_failed.wav", self:GetPos() )
						self:Remove()

						break
					end
				end
			end
			self.PhysicsEnabled = false
		end
```
It checks for existence of single physical material, and then just removes the vehicle if it doesn't exist? And why it's saying to stop using content from other games? That physical material is defined in the gmod's VPK files itself, so the only reason that message will probably show up is that the person accidentaly deleted on of the VPK's or the game files got corrupted somehow.

**Comment by Blu-x92** [comment]
gmod comes with a surfaceproperties.txt that includes all physprop materials of all sourcegames. If someone however, extracts the entire contents of another game (css for example) and merges it with his gmod folder, it will overwrite the original surfaceproperties.txt that includes friction_00 which is required for the vehicles to work. If thats the case, its safe to assume the guy who did that doesnt own css since he should have mounted it through the game menu or, if you are running a server, using mount.txt. 

This check has a successrate of 99.9% of exposing liars and pirates and saved me countless of discussions about whenever or not someone has actually cleaned their game and/or if they are doing some stupid shit with their game and then lie to me about it.

**Comment by 0xadg** [comment]
But doesn't the VPK's surfaceproperties.txt override any other properties file in the scripts folder? Checking its location using `whereis` always returns file path with the VPK file.

**Comment by Blu-x92** [comment]
no it doesnt
